spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exampledb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kris2486!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        #        format_sql: true
        default_batch_fetch_size: 100
    #        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    #    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database: mysql
